### ISSUE TITLE
Review API DTOs

### ISSUE THREAD

**Issue by bonndan** [dedica-team/nivio#137]
- [x] Review landscape DTO for unwanted or missing fields
- [x] evaluate if group DTOs are needed
- [x] evaluate if item DTOs are needed
- [x] document in swagger
- [x] evaluate if generic ObjectMappers can be used for all components instead of DTOs: interfaces like Labeled, Linked... provide "DTO" fields as well
- [x] evalute if Item.links should be HATEOAS links instead

**Comment by bonndan** [comment]
@MarvinSchoening please review the first draft 
[nivio_example.json.zip](https://github.com/dedica-team/nivio/files/4763917/nivio_example.json.zip)

**Comment by MarvinSchoening** [comment]
> @MarvinSchoening please review the first draft
> [nivio_example.json.zip](https://github.com/dedica-team/nivio/files/4763917/nivio_example.json.zip)

Looks good, we still have "providedBy" in items but we discussed to remove it because it was an old feature. Is it used or not?

**Comment by bonndan** [comment]
My bad, should be removed.

**Comment by bonndan** [comment]
Sorry, I accidentally uploaded an outdated JSON example. The recent API does not contain this field anymore.
