### ISSUE TITLE
Revise documentation

### ISSUE THREAD

**Issue by MarvinSchoening** [dedica-team/nivio#138]
Some informations in our documentation aren't up to date and need to be revised or are missing.
e.g.: 
API Endpoints: 
- /api/landscape/{landscape.identifier} is wrong and /api/{landscape.identifier} provides the desired data. 

- /api/ provides all landscapes but isn't listed at all

Tasks:
- [ ] crossread docs for anything that sounds strange or seems unclear, open tickets or fix directly if possible
- [ ] make sure that instructions how to get started with docker are correct and only given in one place (docs, preferably not the readme)

**Comment by mfbieber** [comment]
I would prefer to have a good readme *AND* a proper docs (or manual). I think the readme is read by people landing on GitHub and the manual by people accessing our deployed nivio site.

**Comment by bonndan** [comment]
Sounds reasonable. If the "getting started" section can be kept small and point to the manual for further details, I agree.
