### ISSUE TITLE
Find replacement for file/URL handling classes

### ISSUE THREAD

**Issue by bonndan** [dedica-team/nivio#169]
At the moment nivio uses self written utiity classes to handle URLs, especially to

* check if a URL is local
* check if a URL is valid
* if a path is relative
* to concatenate pathes and base URL

The implementation works, but there might be better ways and libs to do it.

- [ ] research what else is offered by the Java/Spring ecosystem (e.g. util classes shipped with Spring, Apache commons etc.)
- [ ] replace or improve the code
- [ ] assure that tests work under Linux and Windows

Hint: start with the URLHelper class and see where it is used.

**Comment by MarvinSchoening** [comment]
possible solution: https://commons.apache.org/proper/commons-io/javadocs/api-2.5/org/apache/commons/io/FilenameUtils.html
