### ISSUE TITLE
Verify File/URL observer is working

### ISSUE THREAD

**Issue by bonndan** [dedica-team/nivio#179]
* checkout develop
* start under different conditions in DEMO mode
* start using SEED
* modifiy a given config file (e.g. SEED value target)
* modify a source reference file (named inside SEED value target)

- [x] verify works under windows
- [ ] verify works under windows from jar
- [ ] verify works under docker with mounted files

**Comment by mfbieber** [comment]
If I build the jar and start it via `java -jar target/nivio.jar` and providing a SEED environment variable in that shell, `http://localhost:8080` will serve the frontend, but requests to the backend will go to the one deployed on Heroku. This is fine, since we are using the jar only for this purposes, but I think that it should be configurable in case someone really wants to use the jar - what do you think?

**Comment by mfbieber** [comment]
I also noticed that 19:30 is displayed as 07:30, but no information about a.m. or p.m. is displayed. Is this intentional?

**Comment by mfbieber** [comment]
`docker run -e DEMO=1 dedica-team/nivio` will try to pull nivio from docker hub, which does not exist there (Error response from daemon: pull access denied for dedica-team/nivio, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.). As far as I know, we don't have it in a docker registry, do we?

We should update the documentation (the manual) and inform users that they also need to build the image, e.g.:
`docker build -t nivio:version1 .`

**Comment by mfbieber** [comment]
So in general: the backend will notice the changes in  the yml files, but for the jar and the docker container, the changes will not be visible from the frontend delivered by the backend container.

**Comment by bonndan** [comment]
Hi and thanks for the review.

Imho the frontend should always send requests to the same server it is being served from. So this is a bug.

**Comment by mfbieber** [comment]
Yes. The docker-container does not notice changes if you don't volume bind the yml files to the container.

**Comment by mfbieber** [comment]
The jar registers changes if the SEED environment variable has been set on the shell.

**Comment by bonndan** [comment]
I have opened https://github.com/dedica-team/nivio/issues/203

**Comment by bonndan** [comment]
Is volume-binding documented properly?

**Comment by mfbieber** [comment]
And what I said about the docker container: then SEED must refer to the location inside the container. 

Am I missing something? How have we been using nivio from a docker container? Have we ever seen changes of the files with that?

**Comment by mfbieber** [comment]
Ah, yes. In the readme! But not in the Manual which is visible from the frontend. The readme says:
````
git clone https://github.com/dedica-team/nivio.git && cd nivio
  mvn clean package
  docker build -t nivio:latest .
  docker run -e SEED=/tmp/inout.yml --mount type=bind,source=C:\<your>\<path>\<to>\nivio\src\test\resources\example,target=/tmp -p 8080:8080 nivio:latest
````

**Comment by bonndan** [comment]
When running in docker volume bindung is probably the only way to notice filesystem changes (other types will be added later). I'd say running nivio with docker is the primary way to use/try it.

Could you update the manual?

**Comment by mfbieber** [comment]
Yes. I can do it in the next few days!

**Comment by bonndan** [comment]
@mfbieber I've changed the purpose of #150 to clean up instructions, so this ticket can be closed. Thanks for your help!
