### ISSUE TITLE
Improve jump to relation target

### ISSUE THREAD

**Issue by bonndan** [dedica-team/nivio#190]
Evaluate (before implementing)

- [x]  visual feedback on clicked relation (halo, borderhighlight etc)
- [x] do not change zoom level
- [x]  pan (scroll) smoothly to allow visual tracing
- [x] prevent that sidebar overlaps scroll target

**Comment by MarvinSchoening** [comment]
mhmm idk how to implement a smooth transition, the library that we use doesn't support anything like that, i'll think about a way to do it

**Comment by bonndan** [comment]
We could interpolate the whole distance, or we just ask the library author
for advice.

Marvin Schöning <notifications@github.com> schrieb am Mi., 22. Juli 2020,
13:37:
