### ISSUE TITLE
Bottleneck KPI

### ISSUE THREAD

**Issue by bonndan** [dedica-team/nivio#195]
Add a KPI which analyzes number of item relations, both incoming and outgoing.

* rework scaling KPI (it is too superficial)
* differentiate between provider relations (hard) and data flow (soft)

 * red if 0 as provider for other items
 * yellow if scaled to 0 without relations
 * orange of scaled to 0 as data sink
 * unknown if no label or not a number
 * green if scaled higher than 1
 * yellow if a bottleneck (more than 1 item depend on it)

**Comment by MarvinSchoening** [comment]
the user should be able to set his own variables for the evaluation
