### ISSUE TITLE
Rework frontend design

### ISSUE THREAD

**Issue by MarvinSchoening** [dedica-team/nivio#246]
We currently use a heavy mix of our own styling and material-ui. To use all powerful features from material-ui like themes, we should rework our stylings to mostly use material-ui and just style what is really necessary.

- [x] suggest appeareance and/or use improvements with wireframes
- [x] improve smaller aspects by replacing custom elements with Material UI elements
- [x] work towards use of Material UI themes

**Comment by bonndan** [comment]
All points have been addressed in follow-up tickets or are implement in develop branch.
