### ISSUE TITLE
out of memory error while rendering large landscapes

### ISSUE THREAD

**Issue by BilligsterUser** [dedica-team/nivio#257]

**Comment by bonndan** [comment]
Nivio develop branch with PNG caching

![image](https://user-images.githubusercontent.com/143695/92520608-2a3f0280-f21c-11ea-8316-d6f6c6657e50.png)

Without PNG caching (after all we can achieve the same with svgs)

![image](https://user-images.githubusercontent.com/143695/92520672-480c6780-f21c-11ea-8734-b96d6e8cb348.png)

Both running in DEMO mode and have been force-garbage collected once.

**Comment by mfbieber** [comment]
Has that been garbage collected in the Visual VM, or programmatically?
