### ISSUE TITLE
Prepare for Hacktoberfest

### ISSUE THREAD

**Issue by BilligsterUser** [dedica-team/nivio#281]
Information: [https://hacktoberfest.digitalocean.com/details](https://hacktoberfest.digitalocean.com/details)

- Apply the "Hacktoberfest" label to issues in your GitHub project that are ready for new contributors to work on.
- Add a CONTRIBUTING.md file with contribution guidelines to your repository.
- Choose issues that have a well-defined scope and are self-contained.
- Adopt a code of conduct to foster a greater sense of inclusion and community.

**Comment by bonndan** [comment]
- [ ] add instruction how to "glue" nivio to information sources
- [ ] UX tickets
- [ ] Introduction to the code with examples
