### ISSUE TITLE
Remove unused dependencies from pom.xml

### ISSUE THREAD

**Issue by BilligsterUser** [dedica-team/nivio#283]

**Comment by Yelk11** [comment]
Hello, I would like to take on this task. Could you tell me more about what dependencies you want removed? Or how you want me to find the unused dependencies?

**Comment by bonndan** [comment]
Hi and thanks for your offer. Are you taking part in the Hacktoberfest?

After having removed a bigger feature recently, we have a suspicion that the pom still lists libraries we don't need anymore. Our approach would have been to run `dependency:analyze` and see what comes out and might be deleted. Afterwards we'd run all tests and start nivio in the demo mode (set env var DEMO=1).

**Comment by Yelk11** [comment]
Yes, Im participating in Hacktoberfest. I will look into the extra dependencies and submit a pull request after Oct. 1st.

Thank you for the guidance!

**Comment by bonndan** [comment]
Currently no unused dependencies in develop branch.
