### ISSUE TITLE
Overhaul test data

### ISSUE THREAD

**Issue by MarvinSchoening** [dedica-team/nivio#286]
To better demonstrate and develop nivio, our test data needs some more input for things like KPI's, Labels, Links, Groups (pseudo owner etc). We should keep some elements at minimum settings for testing purposes.

* create a pet clinic example with content based on https://github.com/spring-petclinic/spring-petclinic-microservices

- [ ] add db .address field values
- [ ] add frameworks
- [ ] add location label? (physical location)

**Comment by bonndan** [comment]
[Nivio (1).pdf](https://github.com/dedica-team/nivio/files/6525834/Nivio.1.pdf)
