### ISSUE TITLE
Remove status icons (flame, danger etc.)

### ISSUE THREAD

**Issue by bonndan** [dedica-team/nivio#301]
The Status.java enum still has a symbol field for a icon representation, which should not be used anymore.

- [x] remove field
- [x] remove usages, if any
- [x] remove files
- [x] remove copyright statement

**Comment by charberg** [comment]
I'm interested on working on this issue for hacktoberfest if possible! Seems like an easy entry point.

**Comment by bonndan** [comment]
@charberg Great! Please go ahead. Let us know if you need any help.

**Comment by charberg** [comment]
Hey @bonndan , please check out PR here: https://github.com/dedica-team/nivio/pull/313
