### ISSUE TITLE
Trigger event instead of direct use of Indexer an API

### ISSUE THREAD

**Issue by bonndan** [dedica-team/nivio#309]
The ApiController makes direct use of Indexer.java instead of creating an IndexEvent. Therefore, the frontend cannot be notified of changes and the trigger itself is not logged.

**Solution**
Create an IndexEvent in the controller with the proper payload.

**Comment by Ruchika8** [comment]
hi I would like to try this out

**Comment by bonndan** [comment]
Great. If this task turns out to be a bit complicated, do not hesitate ask for assistance.

**Comment by Ruchika8** [comment]
Awesome, thanks!

**Comment by Ruchika8** [comment]
hey I tried out change in a particular api for this. For all apis we return a ProcessLog object to the user. So I have added ProcessLog object within the IndexEvent. Thoughts? 
<img width="483" alt="Screenshot 2020-10-14 at 11 14 34 PM" src="https://user-images.githubusercontent.com/18403024/96025748-33526d80-0e73-11eb-9308-3a484af484c3.png">
<img width="920" alt="Screenshot 2020-10-14 at 11 12 38 PM" src="https://user-images.githubusercontent.com/18403024/96025768-39e0e500-0e73-11eb-96a9-ea7263a6205d.png">

**Comment by bonndan** [comment]
Looks good to me. @mfbieber any thoughts?

**Comment by mfbieber** [comment]
Hi @Ruchika8!

Nice to have you here 😺 

That looks good to me too 👍 

Since the `IndexEvent`s are reported to the frontend through a websockets implementation, the payload of the controller methods stays the same. If all apis generating an `IndexEvent` will return a `ProcessLog`, your idea to locate it in the `IndexEvent` itself is great!

@bonndan: what about the `indexLandscape()` method in `ApiController`? Should that be treated with an `IndexEvent` too?

**Comment by bonndan** [comment]
Hmm... Yes, but I am not sure if this is still needed. I'd say it is out of scope here.

**Comment by mfbieber** [comment]
@Ruchika8: I am looking forward to your pull request 😄

**Comment by Ruchika8** [comment]
Thanks! 😊 I will complete this asap! 👍

**Comment by bonndan** [comment]
Hi @Ruchika8 ! Are you still working on this issue?

**Comment by Ruchika8** [comment]
Oh yes! I was seriously unwell for the past month and had a long recuperation time. Getting better now and will close this asap 👍 🥇

**Comment by Ruchika8** [comment]
hey @bonndan here's the [pr](https://github.com/dedica-team/nivio/pull/345)

**Comment by bonndan** [comment]
done
