### ISSUE TITLE
report.html output requests additional files from localhost using absolute paths

### ISSUE THREAD

**Issue by basseur** [dedica-team/nivio#33]
I have just noticed that the server started by nivio is accessible from the entire local network. So far so good. However, the information in report.html is not displayed correctly, because it seems that absolute paths are used for additional files. CSS and images are requested by localhost, but are of course not available under localhost on a remote computer.

Regardless of whether the page is to be accessible from the entire network or only from the localhost, relative paths should be used.

![grafik](https://user-images.githubusercontent.com/32487587/66739944-31298d80-ee72-11e9-938c-5d415bcf00fb.png)

**Comment by bonndan** [comment]
Please describe how exactly nivio was started. Docker? Other port?

**Comment by basseur** [comment]
It was started using docker and port _8080_ as described in the "Development Setup" section (`docker run -e SEED=/tmp/inout.yml --mount type=bind,source="$(pwd)"/src/test/resources/example,target=/tmp -p 8080:8080 nivio:latest`) and then opening the page from another machine.

I also just noticed that not only _localhost_ but also port _8080_ is hardcoded. I found out by chaning the port using `-p 8099:8080` for example.
This is still true for the latest commit (https://github.com/bonndan/nivio/commit/87ed465df042d5bfd6dccf6406c8964294570cbc)!

![grafik](https://user-images.githubusercontent.com/32487587/67037856-a28d6880-f11e-11e9-8ea3-93edffa535ee.png)

**Comment by bonndan** [comment]
the last commit in develop improves it, but will not fix it completely
