### ISSUE TITLE
Get rid of several type casts by improving the type definition

### ISSUE THREAD

**Issue by bonndan** [dedica-team/nivio#40]
You might be able to get rid of several type casts by improving the type definition here.

E.g. something like:

        private static <T> List<T> findAll(FullyQualifiedIdentifier fqi, Collection<T extends LandscapeItem> items)

_Originally posted by @Matthimatiker in https://github.com/bonndan/nivio/pull/39_

This also applies to several other classes, especially the interface implementations ("description" vs objects used in memory).

**Comment by bonndan** [comment]
#73 should have further improved the situation. Is this sufficient now?

**Comment by Matthimatiker** [comment]
Better now :+1:
