### ISSUE TITLE
Improve landscape update feedback loop

### ISSUE THREAD

**Issue by bonndan** [dedica-team/nivio#435]
As a user trying out nivio I need to see input data changes/updates immediately. Otherwise I have the impression that the system is broken or I did something wrong.

- [x] ensure the file based change observers pick up changes immediately
- [x] ensure websocket based change notification is still working

- see #322

**Comment by bonndan** [comment]
@mfbieber The file observer seems to work as expected. The only way to reproduce the bug is to edit files using IntelliJ, which does not write to files immediately after entering changes.

**Comment by mfbieber** [comment]
> @mfbieber The file observer seems to work as expected. The only way to reproduce the bug is to edit files using IntelliJ, which does not write to files immediately after entering changes.

I can also reproduce it when I edit and explicitly save the file with e.g. notepad :-/
