### ISSUE TITLE
Source folder littered with files after docker run

### ISSUE THREAD

**Issue by basseur** [dedica-team/nivio#44]
I have been running Nivio via the "development setup" instructions and noticed that the source directory gets littered with image files and folders. These files remain even after terminating docker with ctrl+c (is this even the correct way?).

The image file names consist of the landscape name, followed by a random number of different lengths, followed by _png_, but with no extension. A new image file is created for every time, graph.png is requested.

The folders are named _tomcat._ followed by a random number, followed by a period and the port number. It contains the folder structure `./work/Tomcat/localhost/ROOT`, but no files.

Folders named _tomcat-docbase._ followed by a random number, followed by a period and the port number are deleted after terminating docker.

![grafik](https://user-images.githubusercontent.com/32487587/68118354-13df6080-ff00-11e9-9575-fe48c00b61bd.png)

**Comment by bonndan** [comment]
The folders are likely leftovers from https://github.com/spring-projects/spring-boot/issues/9983
What causes the Images to be created ist not clear to me. Maybe temporary files? Have you worked with / called the inout example a Lot?

You could try to replace Tomcat and see of the folders disappear. Or try to Set the tomcat Remo dir. However, once we go micronaut thus problem might be history

**Comment by basseur** [comment]
I failed to mention: The files are images and contain the graph.png. As I've said before, a new copy is created _every_ time, graph.png is requested. Basically, just browsing the server and refreshing creates them. So, yes, I guess they are temporary files that just don't get removed.

Have you not seen those? In IntelliJ, they are shown as unversioned files, which is why I became aware of them in the first place.

**Comment by bonndan** [comment]
When you ran docker, which mounts did you use? Was it the directory where all those files appeared?

**Comment by basseur** [comment]
The files are created in the folder provided by `source=`.
I ran

    docker run -e SEED=/tmp/inout.yml --mount type=bind,source="$(pwd)"/src/test/resources/example,target=/tmp -p 8080:8080 nivio:latest

When I ran Nivio on AdventOfCode (https://github.com/bonndan/nivio/issues/29#issuecomment-541614258), _landscape.yml_ was in the root directory. So, that was where the files/folders where created.
