### ISSUE TITLE
Proofread and improve manual

### ISSUE THREAD

**Issue by bonndan** [dedica-team/nivio#446]
The manual is partially incomplete, not well-structured and the English should be corrected.

**Comment by bonndan** [comment]
@dleidert for your reference

**Comment by dleidert** [comment]
Collection of TODO items coming up during proofread (incomplete and to be extended):

[ ] Rewrite Markdown in readme files (use markup for headers, code, etc.)
[ ] Choose an appropriate texinfo category
[ ] Check if "see ... section" is linking correctly in RST files

**Comment by bonndan** [comment]
@dleidert I am not able to define a proper texinfo category other than the current one. Is there a list of possible categories? All my research leads to nothing.

**Comment by dleidert** [comment]
Some texinfo document refers to https://directory.fsf.org/wiki/Category/All. However, I checked sources in Debian and found only one example so far not using 'Miscellaneous' (it was using 'Programming').

**Comment by bonndan** [comment]
I would keep it as it is for now. Especially if the Debian projects are not really using it.
