### ISSUE TITLE
Custom thickness per connection between items

### ISSUE THREAD

**Issue by hsch** [dedica-team/nivio#565]
It could be interesting to support an individual thickness for each connecting line between groups.

I'm using groups to represent micro services, and the thickness could be a way to visualise the amount of traffic between the linked services.

To be clear, this would be a nice-to-have for me. :)

**Comment by bonndan** [comment]
Could you explain how you get the data on the amount of traffic? What is the source (e.g. grafana, prometheus, ....) and what format does it provide?

Thinking of graphs, we must/should store that information on edges rather than on nodes (what has not been done yet).

**Comment by hsch** [comment]
> Thinking of graphs, we must/should store that information on edges

Yep, I would agree with this.

Currently I'm using a Splunk query (could potentially turn it into a report and retrieve a CSV or so) with the count of service-to-service requests.

Just note that I'd be okay with managing the data, aggregation, normalisation, and transformation to e.g. [0,1] thickness values (or something like that) myself, and then just add a new value per edge to the landscape YAML. Nothing too fancy needed here.

**Comment by bonndan** [comment]
Relates to #543
