### ISSUE TITLE
IndexNotFoundException in Apache Lucene lib

### ISSUE THREAD

**Issue by robrobert99** [dedica-team/nivio#574]
**Describe the bug**
IndexNotFoundException occurs during program execution

**To Reproduce**
1. Execute program with DEMO=1
2. Open application in a web browser 

**Additional context**
It seems the exception appears random, during program use.

[Exception.txt](https://github.com/dedica-team/nivio/files/6662466/Exception.txt)

**Comment by bonndan** [comment]
Suggested solution: replace deprecated RAMDirectory
