### ISSUE TITLE
Map-Assessment and Frontend-Assessment are not synchronized

### ISSUE THREAD

**Issue by robrobert99** [dedica-team/nivio#637]
**Describe the bug**
Map-Assessment and Frontend-Assessment are not synchronized.

**To Reproduce**
The Bug appears when the KubernetesObservers triggers an Update two time or more.

**Expected behavior**
Map-Assessment and Frontend-Assessment should be synchronized.

**Screenshots**
![image](https://user-images.githubusercontent.com/84507051/128515406-bfed1cf0-b3bb-44f8-a5ce-203136a1a0cf.png)

**Comment by bonndan** [comment]
The map reload is lagging...
