### ISSUE TITLE
Relation is not shown after re-indexing

### ISSUE THREAD

**Issue by robrobert99** [dedica-team/nivio#639]
**Describe the bug**
After the re-indexing of the Landscape. The Relation between the replicaSet and the new Pod is not shown.

**To Reproduce**
1. Start Minikube
2. Start Nivio
3. Scale up a deployment

**Expected behavior**
The new relation between replicaSet and new Pod should be visbile

**Screenshots**
![image](https://user-images.githubusercontent.com/84507051/128722154-a31ea365-2f90-4dfb-a728-ebb24611255f.png)

**Comment by bonndan** [comment]
The problem is that items are copied into groups while they also exist in the landscape item index. In the long term we need to get rid of one of the two places.
