### ISSUE TITLE
Wrong commands in development.md

### ISSUE THREAD

**Issue by jenarp** [dedica-team/nivio#673]
Comments from Daniel L.:

Two last commands in development.md might be wrong. 
When executing the first of the two commands:
Error 404 + 
> w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'POST' not supported]

Maybe the issue is due to:
First example's uses API:
http://localhost:8080/api/landscape/
And second example, maybe too? Please, have a look at it.

**Comment by bonndan** [comment]
This isse has already been fixed
