### ISSUE TITLE
Find embeddable database which works with Spring Data

### ISSUE THREAD

**Issue by bonndan** [dedica-team/nivio#849]
As a developer I want to learn how to use Spring Data.

## Acceptance criteria

- [x] find a database which can run embedded and works with standard Spring Data annotations (repos, models...)

**Comment by jenarp** [comment]
Choice: Spring Data JPA with an embedded H2 database

Why:
Spring Data JPA + JPA?

- JPA makes using a database more java-esque as it maps Java objects to relational database tables. By using Spring Data JPA in addition, working with the JPA provider is less verbose and a lot of the boilerplate code is eliminated.

H2 database?

- H2 is embeddable, works with Spring data annotations and there is plenty of literature about it in the web makes it a good candidate for learning database management
